trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/storage/azblob

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/storage/azblob


stages:
  - template: /eng/pipelines/templates/jobs/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: 'storage/azblob'
      RunLiveTests: true
      Location: canadacentral
      CloudConfig:
        Preview:
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview)
        PrivatePreview:
          SubscriptionConfiguration: $(sub-config-storage-test-resources)
      Clouds: Preview
      SupportedClouds: Preview, PrivatePreview
      MatrixReplace:
        # Use dedicated storage pool in canadacentral with higher memory capacity
        - Pool=(.*)-general/$1-storage
